sections:
  main:
    display: Main
    fields:
      -
        handle: logo_header
        field:
          theme: light
          mode: htmlmixed
          indent_type: tabs
          indent_size: 4
          key_map: default
          line_numbers: true
          line_wrapping: true
          type: code
          instructions: 'Paste your svg code from your logo svg file'
          listable: hidden
          display: 'Logo header'
